using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Mutagen.Bethesda;
using Mutagen.Bethesda.Fallout4;
using Mutagen.Bethesda.FormKeys.Fallout4;
using Mutagen.Bethesda.Plugins;
using Mutagen.Bethesda.Synthesis;

namespace FO4StandaloneWorkbenchesPatcher
{
    public static class Program
    {
        private static readonly HashSet<ModKey> Excluded = new()
        {
            ModKey.FromNameAndExtension("ECO.esp"),

            ModKey.FromNameAndExtension("IDEKsLogisticsStation2.esl"),

            ModKey.FromNameAndExtension("Craft Armor.esp"),
            ModKey.FromNameAndExtension("Craft Clothing.esp"),
            ModKey.FromNameAndExtension("Craft Weapons.esp"),
            ModKey.FromNameAndExtension("whisperCraftPowerArmor.esp"),
            ModKey.FromNameAndExtension("whisperCraftingRearranged.esp"),

            ModKey.FromNameAndExtension("dlcammo_craftable.esp"),
            ModKey.FromNameAndExtension("dlcweapons_craftable.esp"),
            ModKey.FromNameAndExtension("vanillaammo_craftable.esp"),
            ModKey.FromNameAndExtension("vanillaminesgrenades_craftable.esp"),
            ModKey.FromNameAndExtension("vanillaweapons_craftable.esp")
        };

        private static readonly HashSet<ModKey> Vanilla = new()
        {
            ModKey.FromNameAndExtension("Fallout4.esp"),
            ModKey.FromNameAndExtension("DLCRobot.esl"),
            ModKey.FromNameAndExtension("DLCworkshop01.esp"),
            ModKey.FromNameAndExtension("DLCCoast.esp"),
            ModKey.FromNameAndExtension("DLCworkshop02.esp"),
            ModKey.FromNameAndExtension("DLCworkshop03.esp"),
            ModKey.FromNameAndExtension("DLCNukaWorld.esp")
        };

        private static Lazy<Settings> _settings;
        private static Settings Settings => _settings.Value;

        public static async Task<int> Main(string[] args)
        {
            return await SynthesisPipeline.Instance
                .AddPatch<IFallout4Mod, IFallout4ModGetter>(RunPatch)
                .SetAutogeneratedSettings("Settings", "settings.json", out _settings)
                .SetTypicalOpen(GameRelease.Fallout4, "StandaloneWorkbenches_Patch.esp")
                .AddRunnabilityCheck(state =>
                {
                    state.LoadOrder.AssertListsMod(StandaloneWorkbenches.ModKey,
                        "\nStandaloneWorkbenches plugin missing, not active, or inaccessible to patcher!\n\n");
                })
                .Run(args);
        }

        public static void RunPatch(IPatcherState<IFallout4Mod, IFallout4ModGetter> state)
        {
            foreach (var cobjContext in state.LoadOrder.PriorityOrder.ConstructibleObject().WinningContextOverrides())
            {
                if (Excluded.Contains(cobjContext.ModKey)) continue;
                if (Settings.NoVanillaItems && Vanilla.Contains(cobjContext.ModKey)) continue;
                if (cobjContext.Record is null) continue;
                if (cobjContext.Record.IsDeleted) continue;

                var cobj = cobjContext.Record;

                if (cobj.WorkbenchKeyword.IsNull) continue;
                if (cobj.CreatedObject.IsNull) continue;

                if (Settings.FromChemistryStationOnly &&
                    cobj.WorkbenchKeyword.FormKey != Fallout4.Keyword.WorkbenchChemlab.FormKey)
                    continue;

                var craftRes = cobj.CreatedObject.TryResolve(state.LinkCache);
                if (craftRes is null || craftRes.IsDeleted) continue;

                FormLink<IKeywordGetter> target = null;

                if (Settings.AmmunitionToAmmunitionWorkbench && craftRes is IAmmunitionGetter)
                {
                    target = StandaloneWorkbenches.Keyword.wSW_AmmunitionWorkbench_CraftingKey;
                }
                else if (Settings.ArmorsToArmorsmithWorkbench && craftRes is IArmorGetter)
                {
                    target = StandaloneWorkbenches.Keyword.wSW_ArmorsmithWorkbench_CraftingKey;
                }
                else if ((Settings.WeaponsToWeaponsmithWorkbench || Settings.ExplosivesToExplosivesWorkbench ||
                          Settings.ExplosivesToWeaponsmithWorkbemch) && craftRes is IWeaponGetter weapon)
                {
                    if (Settings.WeaponsToWeaponsmithWorkbench &&
                        weapon.AnimationType != Weapon.AnimationTypes.Grenade &&
                        weapon.AnimationType != Weapon.AnimationTypes.Grenade)
                    {
                        target = StandaloneWorkbenches.Keyword.wSW_WeaponsmithWorkbench_CraftingKey;
                    }
                    else if (weapon.AnimationType is Weapon.AnimationTypes.Grenade or Weapon.AnimationTypes.Grenade)
                    {
                        if (Settings.ExplosivesToExplosivesWorkbench)
                            target = StandaloneWorkbenches.Keyword.wSW_ExplosivesWorkbench_CraftingKey;
                        else if (Settings.ExplosivesToWeaponsmithWorkbemch)
                            target = StandaloneWorkbenches.Keyword.wSW_WeaponsmithWorkbench_CraftingKey;
                    }
                }
                else if (Settings.AlchemyToUtilityWorkbench && craftRes is IIngestibleGetter)
                {
                    target = StandaloneWorkbenches.Keyword.wSW_UtilityWorkbench_CraftingKey;
                }
                else if (Settings.NotesToUtilityWorkbench && craftRes is IBookGetter or IHolotapeGetter)
                {
                    target = StandaloneWorkbenches.Keyword.wSW_UtilityWorkbench_CraftingKey;
                }
                else if (Settings.MiscToManufacturingAndUtilityWorkbench && craftRes is IMiscItemGetter misc)
                {
                    if (misc.Components is {Count: > 0})
                        target = StandaloneWorkbenches.Keyword.wSW_ManufacturingWorkbench_CraftingKey;
                    else
                        target = StandaloneWorkbenches.Keyword.wSW_UtilityWorkbench_CraftingKey;
                }

                if (target != null && cobj.WorkbenchKeyword.FormKey != target.FormKey)
                {
                    var copy = state.PatchMod.ConstructibleObjects.GetOrAddAsOverride(cobj);
                    copy.WorkbenchKeyword.SetTo(target);
                }
            }
        }
    }
}